name: Release new versions

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[release]')"
    steps:
      - uses: actions/checkout@v3
      - name: Generate files with NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "19"
      - name: Generating files
        run: |
          echo "Installing packages in root dir..."
          yarn install
          echo "Transpiling with tsc..."
          yarn tsc
          cp package.json build
          cp ecosystem.config.cjs build
          echo "Generating 'build.tgz' file..."
          cd build && touch build.tgz && tar --exclude=build.tgz -czvf build.tgz ./
          mv build.tgz ../
          echo "Generated 'build.tgz' file"
          yarn install --production
          REPO_LOC=$PWD
          cd ~
          sudo npm i -g node-prune modclean terser
          cd $REPO_LOC
          echo "Cleaning up node_modules folder..."
          modclean -r && node-prune
          set -e
          EXIT_CODE=0
          for i in `find -name '*.js'`; do echo $i; terser $i -o $i; done || EXIT_CODE=$?
          echo "Exit code was $EXIT_CODE"
          echo "Generating 'build_w_nm_linux.tgz' file..."
          touch build_w_nm_linux.tgz && tar --exclude=build_w_nm_linux.tgz -czvf build_w_nm_linux.tgz ./
          mv build_w_nm_linux.tgz ../
          echo "Generated 'build_w_nm_linux.tgz' file"
          cd ../
      - name: Set tag variable
        id: tag_s
        run: echo "TAG_NAME=$(echo `git log -1 --format="%s"` | cut -d'v' -f2)" >> $GITHUB_OUTPUT
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build.tgz,build_w_nm_linux.tgz"
          bodyFile: "releaseBody.md"
          tag: ${{ steps.tag_s.outputs.TAG_NAME }}
