name: Tests CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.1"
      - name: Testing 🧪
        run: |
          yarn install --frozen-lockfile
          yarn run teste
        env:
          SENDER_MAIL: ${{ secrets.SENDER_MAIL }}
          RECEIVER_MAIL: ${{ secrets.RECEIVER_MAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          AUTH_URI: ${{ secrets.AUTH_URI }}
          TOKEN_URI: ${{ secrets.TOKEN_URI }}
          AUTH_CERT: ${{ secrets.AUTH_CERT }}
          CLIENT_CERT: ${{ secrets.CLIENT_CERT }}

      - name: Upload to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
