name: Update Translations Wiki

on:
  schedule:
    - cron: "0 0 * * 5"
jobs:
  update-translations-wiki:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.1"
      - name: Update Translations wiki
        run: |
          sh tools/update_translations_wiki.sh
        env:
          SENDER_MAIL: ${{ secrets.SENDER_MAIL }}
          RECEIVER_MAIL: ${{ secrets.RECEIVER_MAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          AUTH_URI: ${{ secrets.AUTH_URI }}
          TOKEN_URI: ${{ secrets.TOKEN_URI }}
          AUTH_CERT: ${{ secrets.AUTH_CERT }}
          CLIENT_CERT: ${{ secrets.CLIENT_CERT }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
